### ISSUE TITLE
Do not start

### ISSUE THREAD

**Issue by MyTimeKill** [lukasz1992/asuswrt-r3g#1]
Hello.
Firmware not working. Try on three routers. UART log attach.
[uart.log](https://github.com/lukasz1992/asuswrt-r3g/files/2551823/uart.log)

**Comment by lukasz1992** [comment]
Hi,

1. I am in the process of rebuilding source - the new with binaries should be out in this month. Some bugs still need to be fixed.
2. Please tell me how exactly did you flash firmware and which file (you should use this one larger without -update in name).

**Comment by MyTimeKill** [comment]
Flash firmware strictly according to the instruction. I controlled it from the console "Breed" with the command "nand dump": the kernel registered at the addresses 0x200000 and 0x600000, the rootfs registered at the address 0xА00000. Everything is OK, but it does not work.

**Comment by lukasz1992** [comment]
Yes, I thought the same. Maybe next version I will manage to add autodetection.

**Comment by lukasz1992** [comment]
New image should be able to deal with flashing on both 0x200000 and 0x600000.
