### ISSUE TITLE
no statistic @ Traffic Analyzer - Statistic

### ISSUE THREAD

**Issue by phntms** [lukasz1992/asuswrt-r3g#10]
There is no statistic at the "Traffic Analyzer - Statistic" page.
Not linked to the client list. There is only one option "All Clients" at drop-down menu.
![image](https://user-images.githubusercontent.com/47415147/54034223-9f102700-41b6-11e9-9e1c-f6be62bb0c15.png)

**Comment by lukasz1992** [comment]
The same release was upgraded again; please check it.

If stats do not appear, please wait 70 minutes and recheck.

**Comment by phntms** [comment]
Solved. Great! Thanks!

**Comment by lukasz1992** [comment]
Thanks for testing
