### ISSUE TITLE
5G signal

### ISSUE THREAD

**Issue by qslfz** [lukasz1992/asuswrt-r3g#11]
5G signal is easy to be lost after restart.

**Comment by lukasz1992** [comment]
Please provide me a better description of a problem:
- which device do you use, and which device do you restart
- what is the distance between device and router
- how many devices are connected to 5GHz WiFi, does it affect all of them?

**Comment by qslfz** [comment]
No matter how far the device is from the router and how many devices and routers are connected, it is easy to lose 5g signal when setting automatic restart and power off restart. Therefore, it is necessary to change the signal to apply Settings to restart 5g.

**Comment by lukasz1992** [comment]
Do I understand it right, that 5GHz radio does not show up after scheduled restart, but 2.4GHz radio does?

Please give me:
- screenshoot of the automatic restart settings page
- explanation why do you need to turn it on?
- dmesg log (from UART if possible)

**Comment by qslfz** [comment]
After the test, set the timer to restart. After the restart, the Windows PC can normally find and connect to 5G signal, but neither the android tablet or mobile phone wireless wan can find 5G signal normally, let alone connect to 5G signal. The ipad and iphone normally find 5G signals and can connect. At this point, the visitor network is not enabled.

System Log - General Log：
Mar 26 21:34:21 rc_service: ntp 433:notify_rc restart_diskmon
Mar 26 21:34:21 rc_service: waitting "start_firewall" via udhcpc ...
Mar 26 21:34:22 miniupnpd[373]: shutting down MiniUPnPd
Mar 26 21:34:22 miniupnpd[373]: chain VUPNP not found
Mar 26 21:34:22 nat: apply nat rules (/tmp/nat_rules_eth3_eth3)
Mar 26 21:34:23 kernel: nf_conntrack_rtsp v0.7 loading
Mar 26 21:34:23 miniupnpd[507]: version 1.9 started
Mar 26 21:34:23 miniupnpd[507]: HTTP listening on port 59703
Mar 26 21:34:23 miniupnpd[507]: Listening for NAT-PMP/PCP traffic on port 5351
Mar 26 21:34:23 disk_monitor: Finish
Mar 26 21:34:24 rc_service: udhcpc 420:notify_rc start_upnp
Mar 26 21:34:24 rc_service: waitting "stop_upnp" via udhcpc ...
Mar 26 21:34:24 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:34:24 miniupnpd[507]: shutting down MiniUPnPd
Mar 26 21:34:24 disk monitor: be idle
Mar 26 21:34:25 miniupnpd[519]: version 1.9 started
Mar 26 21:34:25 miniupnpd[519]: HTTP listening on port 34892
Mar 26 21:34:25 miniupnpd[519]: Listening for NAT-PMP/PCP traffic on port 5351
Mar 26 21:34:25 dhcp client: bound 192.168.1.37 via 192.168.1.1 during 86400 seconds.
Mar 26 21:34:25 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:25 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:25 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:25 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:25 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:34:27 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:34:28 kernel: update_associated_mac_entry(): Peer's PhyCap=>Mode:VHT, BW:80M
Mar 26 21:34:28 kernel: WpaEAPOLKeyAction: CliIdx == 0xFF  pHeader->Addr2(0C-8B-FD-CB-DC-57) !!!
Mar 26 21:34:28 kernel: Receive EAPoL-Key frame from STA 0C-8B-FD-CB-DC-57 wcid(1)
Mar 26 21:34:28 kernel: WpaEAPOLKeyAction: CliIdx == 0xFF  pHeader->Addr2(0C-8B-FD-CB-DC-57) !!!
Mar 26 21:34:28 kernel: Receive EAPoL-Key frame from STA 0C-8B-FD-CB-DC-57 wcid(1)
Mar 26 21:34:28 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:34:30 kernel: BA - Send ADDBA request. StartSeq = 2,  FrameLen = 33. BufSize = 64
Mar 26 21:34:31 kernel: Rcv Wcid(1) AddBAReq
Mar 26 21:34:31 kernel: Start Seq = 00000072
Mar 26 21:34:34 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:34:38 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:38 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:38 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:38 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:38 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:34:38 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:34:38 kernel: Start Seq = 00000000
Mar 26 21:34:38 kernel: BA - Send ADDBA request. StartSeq = 2,  FrameLen = 33. BufSize = 64
Mar 26 21:34:38 kernel: BA - Send ADDBA request. StartSeq = 2,  FrameLen = 33. BufSize = 64
Mar 26 21:34:38 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:34:38 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:34:39 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:34:39 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:39 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:39 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:39 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:39 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:34:39 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:34:41 kernel: BA - Send ADDBA request. StartSeq = c,  FrameLen = 33. BufSize = 64
Mar 26 21:34:44 kernel: Rcv Wcid(8) AddBAReq
Mar 26 21:34:44 kernel: Start Seq = 00000015
Mar 26 21:34:45 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:34:46 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:46 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:46 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:46 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:46 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:34:46 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:34:46 kernel: Start Seq = 00000000
Mar 26 21:34:46 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:34:46 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:34:46 kernel: Start Seq = 00000002
Mar 26 21:34:46 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:34:47 kernel: BA - Send ADDBA request. StartSeq = e,  FrameLen = 33. BufSize = 64
Mar 26 21:34:49 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:34:56 kernel: BA - Send ADDBA request. StartSeq = 10,  FrameLen = 33. BufSize = 64
Mar 26 21:34:58 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:58 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:58 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:34:58 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:34:58 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:34:58 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:34:58 kernel: Start Seq = 00000000
Mar 26 21:34:58 kernel: BA - Send ADDBA request. StartSeq = 2,  FrameLen = 33. BufSize = 64
Mar 26 21:34:59 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:34:59 kernel: Start Seq = 00000002
Mar 26 21:34:59 crond[319]: time disparity of 468509 minutes detected
Mar 26 21:35:01 kernel: BA - Send ADDBA request. StartSeq = 0,  FrameLen = 33. BufSize = 64
Mar 26 21:35:01 kernel: MtPsRedirectDisableCheck(475): [wlan_idx=0x7] PS Redirect mode(pfgForce = 1) is enabled. Send PC Clear command to FW.
Mar 26 21:35:01 kernel: ---->CmdPsRetrieveStartRspFromCR Entry(wcid=7) left.
Mar 26 21:35:04 kernel: Rcv Wcid(6) AddBAReq
Mar 26 21:35:04 kernel: Start Seq = 00000002
Mar 26 21:35:08 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:35:08 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:35:08 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:35:08 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:35:08 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:35:08 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:35:08 kernel: Start Seq = 00000000
Mar 26 21:35:08 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:35:08 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:35:08 kernel: Start Seq = 00000002
Mar 26 21:35:09 kernel: BA - Send ADDBA request. StartSeq = 0,  FrameLen = 33. BufSize = 64
Mar 26 21:35:12 kernel: BA - Send ADDBA request. StartSeq = 12,  FrameLen = 33. BufSize = 64
Mar 26 21:35:17 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:35:23 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:35:27 kernel: BA - Send ADDBA request. StartSeq = 13,  FrameLen = 33. BufSize = 64
Mar 26 21:35:31 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:35:31 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:35:31 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:35:31 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:35:31 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:35:31 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:35:34 kernel: Rcv Wcid(8) AddBAReq
Mar 26 21:35:34 kernel: Start Seq = 0000001f
Mar 26 21:35:42 kernel: BA - Send ADDBA request. StartSeq = 15,  FrameLen = 33. BufSize = 64
Mar 26 21:35:44 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:35:47 kernel: BA - Send ADDBA request. StartSeq = 16,  FrameLen = 33. BufSize = 64
Mar 26 21:35:51 kernel: Rcv Wcid(7) AddBAReq
Mar 26 21:35:51 kernel: Start Seq = 00000000
Mar 26 21:35:52 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:35:52 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:35:52 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:35:52 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:35:52 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:35:53 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:35:54 kernel: Rcv Wcid(8) AddBAReq
Mar 26 21:35:54 kernel: Start Seq = 00000015
Mar 26 21:35:56 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:35:57 kernel: BA - Send ADDBA request. StartSeq = 17,  FrameLen = 33. BufSize = 64
Mar 26 21:36:11 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:36:11 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:36:11 kernel: MtAsicACQueue: Write CR:21510, Value=10421
Mar 26 21:36:11 kernel: MtAsicACQueue: Write CR:21500, Value=10421
Mar 26 21:36:11 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:36:11 kernel: BA - Send ADDBA request. StartSeq = 3,  FrameLen = 33. BufSize = 64
Mar 26 21:36:12 kernel: BA - Send ADDBA request. StartSeq = 18,  FrameLen = 33. BufSize = 64
Mar 26 21:36:15 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Mar 26 21:36:28 kernel: BA - Send ADDBA request. StartSeq = 19,  FrameLen = 33. BufSize = 64
Mar 26 21:36:43 kernel: BA - Send ADDBA request. StartSeq = 1a,  FrameLen = 33. BufSize = 64
Mar 26 21:36:48 kernel: BA - Send ADDBA request. StartSeq = 1c,  FrameLen = 33. BufSize = 64
Mar 26 21:36:58 kernel: BA - Send ADDBA request. StartSeq = 1d,  FrameLen = 33. BufSize = 64
Mar 26 21:37:13 kernel: BA - Send ADDBA request. StartSeq = 1e,  FrameLen = 33. BufSize = 64
Mar 26 21:37:28 kernel: BA - Send ADDBA request. StartSeq = 1f,  FrameLen = 33. BufSize = 64
Mar 26 21:37:33 kernel: Rcv Wcid(8) AddBAReq
Mar 26 21:37:33 kernel: Start Seq = 0000004e
Mar 26 21:37:43 kernel: BA - Send ADDBA request. StartSeq = 20,  FrameLen = 33. BufSize = 64
Mar 26 21:37:48 kernel: BA - Send ADDBA request. StartSeq = 21,  FrameLen = 33. BufSize = 64
Mar 26 21:37:58 kernel: BA - Send ADDBA request. StartSeq = 22,  FrameLen = 33. BufSize = 64
Mar 26 21:38:13 kernel: BA - Send ADDBA request. StartSeq = 23,  FrameLen = 33. BufSize = 64
Mar 26 21:38:28 kernel: BA - Send ADDBA request. StartSeq = 24,  FrameLen = 33. BufSize = 64
Mar 26 21:38:43 kernel: BA - Send ADDBA request. StartSeq = 25,  FrameLen = 33. BufSize = 64
Mar 26 21:38:48 kernel: BA - Send ADDBA request. StartSeq = 26,  FrameLen = 33. BufSize = 64
Mar 26 21:38:56 kernel: BA - Send ADDBA request. StartSeq = 28,  FrameLen = 33. BufSize = 64
Mar 26 21:39:13 kernel: BA - Send ADDBA request. StartSeq = 29,  FrameLen = 33. BufSize = 64
Mar 26 21:39:28 kernel: BA - Send ADDBA request. StartSeq = 2a,  FrameLen = 33. BufSize = 64
Mar 26 21:39:43 kernel: BA - Send ADDBA request. StartSeq = 2b,  FrameLen = 33. BufSize = 64
Mar 26 21:39:48 kernel: BA - Send ADDBA request. StartSeq = 2c,  FrameLen = 33. BufSize = 64
Mar 26 21:39:58 kernel: BA - Send ADDBA request. StartSeq = 2d,  FrameLen = 33. BufSize = 64
Mar 26 21:40:10 kernel: update_associated_mac_entry(): Peer's PhyCap=>Mode:VHT, BW:80M
Mar 26 21:40:12 kernel: Rcv Wcid(2) AddBAReq
Mar 26 21:40:12 kernel: Start Seq = 00000000
Mar 26 21:40:12 kernel: WpaEAPOLKeyAction: CliIdx == 0xFF  pHeader->Addr2(90-3C-92-07-0D-CD) !!!
Mar 26 21:40:12 kernel: Receive EAPoL-Key frame from STA 90-3C-92-07-0D-CD wcid(2)
Mar 26 21:40:12 kernel: WpaEAPOLKeyAction: CliIdx == 0xFF  pHeader->Addr2(90-3C-92-07-0D-CD) !!!
Mar 26 21:40:12 kernel: Receive EAPoL-Key frame from STA 90-3C-92-07-0D-CD wcid(2)
Mar 26 21:40:12 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:40:12 kernel: Rcv Wcid(2) AddBAReq
Mar 26 21:40:12 kernel: Start Seq = 00000000
Mar 26 21:40:13 kernel: BA - Send ADDBA request. StartSeq = 2e,  FrameLen = 33. BufSize = 64
Mar 26 21:40:18 kernel: update_associated_mac_entry(): Peer's PhyCap=>Mode:VHT, BW:80M
Mar 26 21:40:18 kernel: update_associated_mac_entry(): Peer's OperatingMode=>RxNssType: 0, RxNss: 1, ChBW: 0
Mar 26 21:40:18 kernel: WpaEAPOLKeyAction: CliIdx == 0xFF  pHeader->Addr2(84-89-AD-58-BB-98) !!!
Mar 26 21:40:18 kernel: Receive EAPoL-Key frame from STA 84-89-AD-58-BB-98 wcid(3)
Mar 26 21:40:18 kernel: WpaEAPOLKeyAction: CliIdx == 0xFF  pHeader->Addr2(84-89-AD-58-BB-98) !!!
Mar 26 21:40:18 kernel: Receive EAPoL-Key frame from STA 84-89-AD-58-BB-98 wcid(3)
Mar 26 21:40:18 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Mar 26 21:40:18 kernel: Rcv Wcid(3) AddBAReq
Mar 26 21:40:18 kernel: Start Seq = 00000002
Mar 26 21:40:27 kernel: Rcv Wcid(3) AddBAReq
Mar 26 21:40:27 kernel: Start Seq = 00000000
Mar 26 21:40:27 kernel: Rcv Wcid(3) AddBAReq
Mar 26 21:40:27 kernel: Start Seq = 00000001
Mar 26 21:40:28 kernel: BA - Send ADDBA request. StartSeq = 2f,  FrameLen = 33. BufSize = 64
Mar 26 21:40:43 kernel: BA - Send ADDBA request. StartSeq = 30,  FrameLen = 33. BufSize = 64
Mar 26 21:40:48 kernel: BA - Send ADDBA request. StartSeq = 31,  FrameLen = 33. BufSize = 64
Mar 26 21:40:58 kernel: BA - Send ADDBA request. StartSeq = 32,  FrameLen = 33. BufSize = 64
Mar 26 21:41:13 kernel: BA - Send ADDBA request. StartSeq = 33,  FrameLen = 33. BufSize = 64
Mar 26 21:41:29 kernel: BA - Send ADDBA request. StartSeq = 34,  FrameLen = 33. BufSize = 64
Mar 26 21:41:44 kernel: BA - Send ADDBA request. StartSeq = 35,  FrameLen = 33. BufSize = 64
Mar 26 21:41:49 kernel: BA - Send ADDBA request. StartSeq = 36,  FrameLen = 33. BufSize = 64
Mar 26 21:41:59 kernel: BA - Send ADDBA request. StartSeq = 37,  FrameLen = 33. BufSize = 64
Mar 26 21:42:14 kernel: BA - Send ADDBA request. StartSeq = 38,  FrameLen = 33. BufSize = 64
Mar 26 21:42:29 kernel: BA - Send ADDBA request. StartSeq = 39,  FrameLen = 33. BufSize = 64
Mar 26 21:42:44 kernel: BA - Send ADDBA request. StartSeq = 3a,  FrameLen = 33. BufSize = 64
Mar 26 21:42:49 kernel: BA - Send ADDBA request. StartSeq = 3b,  FrameLen = 33. BufSize = 64
Mar 26 21:42:59 kernel: BA - Send ADDBA request. StartSeq = 3c,  FrameLen = 33. BufSize = 64
Mar 26 21:43:12 kernel: BA - Send ADDBA request. StartSeq = 3e,  FrameLen = 33. BufSize = 64
Mar 26 21:43:29 kernel: BA - Send ADDBA request. StartSeq = 3f,  FrameLen = 33. BufSize = 64
Mar 26 21:43:44 kernel: BA - Send ADDBA request. StartSeq = 40,  FrameLen = 33. BufSize = 64
Mar 26 21:43:49 kernel: BA - Send ADDBA request. StartSeq = 41,  FrameLen = 33. BufSize = 64
Mar 26 21:43:59 kernel: BA - Send ADDBA request. StartSeq = 42,  FrameLen = 33. BufSize = 64
Mar 26 21:44:14 kernel: BA - Send ADDBA request. StartSeq = 43,  FrameLen = 33. BufSize = 64
Mar 26 21:44:29 kernel: BA - Send ADDBA request. StartSeq = 44,  FrameLen = 33. BufSize = 64
Mar 26 21:44:44 kernel: BA - Send ADDBA request. StartSeq = 45,  FrameLen = 33. BufSize = 64
Mar 26 21:44:49 kernel: BA - Send ADDBA request. StartSeq = 46,  FrameLen = 33. BufSize = 64
Mar 26 21:44:50 rc_service: httpd 323:notify_rc email_info
Mar 26 21:44:59 kernel: BA - Send ADDBA request. StartSeq = 47,  FrameLen = 33. BufSize = 64
Mar 26 21:45:14 kernel: BA - Send ADDBA request. StartSeq = 48,  FrameLen = 33. BufSize = 64
Mar 26 21:45:29 kernel: BA - Send ADDBA request. StartSeq = 49,  FrameLen = 33. BufSize = 64

**Comment by qslfz** [comment]
![snap_screen_20190326215637](https://user-images.githubusercontent.com/46432857/55002773-23b1d080-5012-11e9-8781-7e175baea53a.png)

**Comment by lukasz1992** [comment]
I think there are 2 possible reasons:
- some chips/drivers prefer to stick to 2.4GHz band and do not try to scan 5GHz band
- problems with DFS or channel regulation problems

Could you set 5GHz channel to 40 and repeat tests?

**Comment by qslfz** [comment]
Set the 5GHz channel to 40 to restart automatically, and the 5g channel will be normal after restart.

**Comment by lukasz1992** [comment]
So is it better now?

**Comment by qslfz** [comment]
Yes, but as a perfectionist, I always feel like it's not perfect to have to specify 5G band 40. This firmware is one of the most efficient and stable I've tested for wireless speed.

**Comment by lukasz1992** [comment]
@qslfz Of course, your answer just gave me idea what is actually wrong. Probably channel autoselection selects channel that is not allowed in your country. I think that some device drivers are not aware about location (Windows), some probably trusts AP driver and others refuse to switch to forbidden channels (Android).

Please confirm:
- You have previously set channel autoselection for 5GHz
- After restart, your Android device is unable to find your 5GHz network again. Refreshing network list does not help, and you have to log into the router and manually change something.
Is all of these right?

Please provide me what is your country. It is not a political question, I just need to know list of allowed channels.

**Comment by qslfz** [comment]
Yes, I'm sure. My country is China.

**Comment by qslfz** [comment]
In future updates, are you considering or can you add functions supporting Repeater and DualWAN?

**Comment by qslfz** [comment]
Firmware is not perfect, is to use asustek (asus router app) connection login, even connected to more than ten different devices, the customer service is still displayed as 0 customer service.

**Comment by lukasz1992** [comment]
@qslfz 
Three things:
1) Repeater and DualWAN is now impossible - if you look at any GPL source from Asus about MT7621 device, the Repeater is always implemented in binary bloob or does not exist. DualWAN is not implemented on MT7621 on Asus devices. So I have no sources to integrate, and therefore I will not add these
2) I have never tried Asus router app; but Xiaomi 3G Router is not Asus device
3) Let me introduce you in detailed description of the problem:
- Every router for MT76XX device has a partition with EEPROM for wireless driver - it is stored in flash
- This partition contains necessary WLAN calibration data, but also some other params
- ASUS use one of this param to provide country information
- ASUS controller read this information and passes it to wireless driver (mt76x2)
- XIAOMI lacks this parameter, so ASUS controller is unable to check the country
- In that case ASUS controller sets country to DB (debug) which allows all channels and passes that information to the driver
- Driver assumes that all channels are available and select one that is not allowed (it is probably free, so the best match for automatic channel selection)
- Your device does not hop to disallowed channel and could not see 5G WLAN
- Asus firmware has no option to specify country

Solution presented in a024891eb5e220249f68e398428eb7cbf294c86e is OK for EU, but not sufficient for China. Because Asus firmware does not allow to specify country, as a workarounds you can:
- Select specific channel for 5GHz
- Directly modify NAND flash at specified address (0x00100188) to program country code - you have to replace 0xFF with these 2 ASCII characters: "CN"

**Comment by lukasz1992** [comment]
@qslfz You can check 3.0.0.4_382_51335 release.

I confirm that Asus app has a hardcoded whitelist of supported models, Xiaomi R3G will never be supported.
I added a 5Ghz fix, maybe it could also work for China.

**Comment by qslfz** [comment]
I'm sorry for the error in the last test. Even if the bandwidth was set to 40Mhz, the 5G Band was still lost after the reset. After the update, the android device could not find the 5G Channel after the reset.

**Comment by lukasz1992** [comment]
@qslfz 
1. I think all channels allowed in China on 5GHz are 36-64. EU allows 100-128, but some of my devices have limited power. I will try to exclude U-NII-2C from channel autoselection in Mediatek driver.
2. I installed ASUS app and see my router R3G Asus app is somehow working.

**Comment by qslfz** [comment]
译文
After the update, the factory Settings have been restored. 5g channels can only be found and connected by android devices with a specified 40mhz, but the transmission rate has been greatly reduced.

**Comment by qslfz** [comment]
According to relevant information, only 149, 153, 157, 161 and 165 5G channels are available in China.

**Comment by qslfz** [comment]
Adjusting the bandwidth reset will lose 5g channels. It has been temporarily tested. It specifies that the Control Channel should be between 36 and 64.

**Comment by qslfz** [comment]
In a simple test, if the bandwidth of the Channel was set to 40mhz, 5g bandwidth could not be found after the bandwidth was reset. If you specify that the Control Channel is between 36 and 64, restart and you can normally find and connect to the 5g Channel. Set Control Channel to 136. 5g Channel cannot be found after restart.

**Comment by qslfz** [comment]
In a simple test, if the bandwidth of the Channel was set to 40mhz, 5g bandwidth could not be found after the bandwidth was reset. If you specify that the Control Channel is between 36 and 64, restart and you can normally find and connect to the 5g Channel. Set Control Channel to 100-140. 5g Channel cannot be found after restart.

**Comment by lukasz1992** [comment]
@qslfz Please use fixed channel number for 5GHz (below 100), as I am not able to fix it correctly (workarounds make serious limitations).
