### ISSUE TITLE
2.4G and usb3.0

### ISSUE THREAD

**Issue by qslfz** [lukasz1992/asuswrt-r3g#12]
In asus router, the function of reducing the interference of USB3.0 is to control the performance of the router USB3.0, so that the router model will not be greatly affected, so as to enhance the signal performance of 2.4g. Can MI R3G do this?

**Comment by lukasz1992** [comment]
Yes, fix in 2062f95f092a94c29a2d52eb89000d355789ed67. The setting will appear on Administration -> System menu. Without that fix, you can still control the setting with:
`nvram set usb_usb3=1` (or 0) - it is just hidden.
