### ISSUE TITLE
L2tp/Ipsec

### ISSUE THREAD

**Issue by tigerthetoni** [lukasz1992/asuswrt-r3g#13]
Is it posible to implement L2tp with Ipsec for VPN client use. On other routers using Asuswrt this is working. On your builds for r3g it is missing.

**Comment by lukasz1992** [comment]
@tigerthetoni Could you provide me screenshoot for other Asus router of this feature and provide me model name which has l2tp with ipsec?

**Comment by tigerthetoni** [comment]
I saw it on a Asus RT-AC86U.

![ipsec](https://user-images.githubusercontent.com/49845482/56680156-ff0b5000-66c6-11e9-90c6-c03bad99bd6f.png)

**Comment by tigerthetoni** [comment]
Sorry, my fault.
Asuswrt IPSEC-enabled models are only RT-AC88U, RT-AC3100, RT-AC5300 and RT-AC86U.

The r3g has the wrong chipset.
