### ISSUE TITLE
Fix the 3.0.0.4_382_5159 version failure to boot

### ISSUE THREAD

**Issue by qslfz** [lukasz1992/asuswrt-r3g#14]
3.0.0.4_382_51599 the firmware of this version is defective. After the brush, the wireless signal is lost after the start of mi r3g, and the LAN port does not respond.

**Comment by phntms** [comment]
+1  
I've updated from the "Administration - Firmware Upgrade" page. Completely lost the device.
The same issue with update from the breed.

**Comment by lukasz1992** [comment]
I am very sorry - I just deleted the faulty release.
The problem must have been with build process, not the source.

Dodaj anyone managed to check serial log?

**Comment by lukasz1992** [comment]
I used the wrong toolchain to compile kernel for faulty release; I just uploaded the correct image.

**Comment by qslfz** [comment]
Thank you for fixing the bug, normal startup, no problem found. When the next version is updated, can we add 149, 153, 157, 161 and 165 channels to the 5g channel?

**Comment by lukasz1992** [comment]
@qslfz Please:
- update image again (new image was just uploaded with the same name)
- log into the router
- run these commands:
`nvram set wl_country_code=CN; nvram set wl0_country_code=CN; nvram set wl1_country_code=CN; nvram commit; reboot`
- after reboot, change the channel as necessary

**Comment by qslfz** [comment]
According to your instructions, the problem of 5g signal has been solved in the designated regional countries. The padavan and meilin have a set function in the 5g Settings called Region Code that allows you to specify the Region country on a web page, which is set to USA by default.

**Comment by qslfz** [comment]
According to your instructions, the problem of 5g signal has been solved in the designated regional countries. In the setting of 5g, padavan and meilin have a setting function of Region Code, which can specify the Region country in the web page. The default setting is USA. Can this function be added in the asuswrt compiled by you?

**Comment by lukasz1992** [comment]
@qslfz I am afraid not in my voluntary work. The reason is that no ASUS router uses this setting (the part of code is never activated) - because all have region programmed in flash. It needs to be reverse-engineered.

If you are determined for many tries and faliures with compiling the source code, I can point you what needs to be changed. In that case please open new Issue again. Otherwise, please change location by nvram command.
