### ISSUE TITLE
Issues with copyright

### ISSUE THREAD

**Issue by LilyFlower10** [lukasz1992/asuswrt-r3g#15]
The repository states that it is a violation of copyright laws and ownership yet is posted in violation of laws, could you remove it for the safety of the internet?

**Comment by lukasz1992** [comment]
> @LilyFlower10 The repository states that it is a violation of copyright laws and ownership yet is posted in violation of laws
Hi @LilyFlower10. Nobody has already contacted me regarding to this.
Could you point me to that posts or explaination of violation?

**Comment by LilyFlower10** [comment]
Apologies, just saw your response today. There are a variety of branches under https://github.com/lukasz1992/asuswrt-r3g/blob/master/release/src/router/APP-IPK/
that specifically state "The author disclaims copyright to this source code.  In place of a legal notice, here is a blessing:" stating that you do not own the copyright for this source code yet you post it.

**Comment by lukasz1992** [comment]
@LilyFlower10
These files come from unmodified GPL dump from Asus, without any modifications.

Asus puts many binary files in GPL dumps without source code. So publishing them here is not against the law.

Do you agree with my opinion?

**Comment by miko1282** [comment]
I am so sorry that I write here, I will remove it Lukasz1992 could you contact me?

**Comment by lukasz1992** [comment]
@miko1282 what is the case?

**Comment by miko1282** [comment]
could You write to me by email?

**Comment by miko1282** [comment]
Hey, can you write in Polish?

pon., 13 maj 2019, 08:38 użytkownik lukasz1992 <notifications@github.com>
napisał:
