### ISSUE TITLE
Overclocking

### ISSUE THREAD

**Issue by matt2k7** [lukasz1992/asuswrt-r3g#16]
I've seen many people overclock their MI-R3G to 1100MHz safely, I even tried it myself on Padavan and it works. I just wanted to know is there a way to achieve the same on your build ? Thanks a lot.

**Comment by lukasz1992** [comment]
Hi, It is not possible with AsusWRT interface.

Anyway you can always compile https://github.com/mitchamador/rt-n56u/blob/master/mt7621_cpufreq.c or just copy https://github.com/mitchamador/rt-n56u/blob/master/mt7621_cpufreq into /jffs. Use /jffs/.asusrouter file as autorun script.
