### ISSUE TITLE
5G信号没问题但是 300M的宽带速度只能跑到180Mbps。换别的固件就能跑到300Mbps

### ISSUE THREAD

**Issue by cnqdmght** [lukasz1992/asuswrt-r3g#20]
你好，5G信号没问题，但是 300M的宽带速度只能跑到180Mbps。换别的固件就能跑到300Mbps，试过改信道之类的始终不行。不知道 老大有没有好的办法或者 我哪里设置不对？对比过潘多拉和老毛子都能跑到300左右

**Comment by lukasz1992** [comment]
我从Padavan github上获取了它们，因为我无法访问Pandora源代码。 而且我只移植了它们-我不是WiFi驱动程序的开发人员

无论如何，我现在检查了一下-我能够在5GHz WiFi上获得300Mbit（速度测试）。

![obraz](https://user-images.githubusercontent.com/13104955/70260128-ef410780-178f-11ea-9313-fb11473cc333.png)

**Comment by cnqdmght** [comment]
感谢回复，因为我有二个R3G，我开始以为是硬件的问题，之前2个都刷过，结果是一样的速率，昨天我把其中一个又重新刷了二次固件，然后就按引导设置了（我现在用来当AP)，竟然可以满速了。真的好奇怪，可能是之前刷机有残留文件吧。

**Comment by lukasz1992** [comment]
我忘记了一件事-802.11ac模式仅适用于N / AC

它有帮助，您能解决问题吗？

**Comment by cnqdmght** [comment]
> 我忘记了一件事-802.11ac模式仅适用于
> 
> 它有帮助，您能解决问题吗？

我现在是这样设置的，能跑满速度了
![Jietu20191206-220016](https://user-images.githubusercontent.com/48038881/70328430-fe00ea80-1873-11ea-993e-06cae327079d.jpg)
![2](https://user-images.githubusercontent.com/48038881/70328439-035e3500-1874-11ea-9c1b-7d7d14fd8c97.jpg)

**Comment by lukasz1992** [comment]
我不知道

我很高興它有效。
