### ISSUE TITLE
Update to 3.0.0.4.382.52072 and switch again to RT-AC85U

### ISSUE THREAD

**Issue by lukasz1992** [lukasz1992/asuswrt-r3g#22]
Current master will be deleted and rewritten for the new base, when Asus releases new GPL archive.

**Comment by adamnickster** [comment]
@lukasz1992 Hi, Could you please include the IPTV section (at least primitive udpxy support without VLAN and switch config)?

**Comment by lukasz1992** [comment]
> @lukasz1992 Hi, Could you please include the IPTV section (at least primitive udpxy support without VLAN and switch config)?
I decided to disable support for it, because I could not find any reference ASUS device with only 2 ethernet ports and same chip (MT7621) and I could not test this functionality

**Comment by adamnickster** [comment]
Can you tell me how can I test it? When I compile from source with  _NOIPTV=y_ removed from target.mak, in output3 I get this error: 
```
HTML file : /home/adam/asuswrt/release/src-ra-5010/router/mipsel-uclibc/install/www/www/Advanced_IPTV_Content.asp

HTML_PREP_ELSE no found
HTML_PREP_END no found
Done!
```
And in trx image is missing file: Advanced_IPTV_Content.asp

**Comment by adamnickster** [comment]
Multicast routing (IGMP Proxy) and Efficient multicast forwarding (IGMP Snooping)  - works well, also on WiFi

ISP Profile - None - I can't test it
IPTV STB Port - I don't use LAN ports - only udpxy proxy / igmp proxy

I think you can safely enable the section "Special Applications" on the IPTV tab.

**Comment by lukasz1992** [comment]
Done in 3.0.0.4_382_52072
