### ISSUE TITLE
Universal Beamforming 

### ISSUE THREAD

**Issue by alexdzn2008** [lukasz1992/asuswrt-r3g#23]
Universal Beamforming not working on MI-R3G, can't enable it....

**Comment by lukasz1992** [comment]
Can you describe the problem? Which release did you try?
Passing configuration to driver should be fixed in last release, but I don't know how to check if it is actually working

**Comment by alexdzn2008** [comment]
Latest pre-release 52072 on mi-r3g in configuration 5G I try to switch on Universal Beamforming option  and UI shows disabled, every time after enable it...by the way speed test is lower in compare to latest 599 release (270 Mbit/220 Mbit), 52072 gives 160-180 Mbit / 160 Mbit....

**Comment by lukasz1992** [comment]
Thanks for clarification. Please try the following:
- enter to console, type
`nvram show | grep txbf | sort`
`cat /etc/Wireless/iNIC/iNIC_ap.dat | grep Bf`
and provide me outputs - after that we will see what to do next

The second option (Universal Beamforming) will probably never work on 3G router, as this needs special calibration data, which 3G router does not have. I missed commit to hide this option in UI.

**Comment by lukasz1992** [comment]
@alexdzn2008 We will try to disable Universal beamforming option by nvram command and check performance with explicit txbf settings.

**Comment by alexdzn2008** [comment]
alexdzn@RT-MIR3G:/tmp/home/root# nvram show | grep txbf | sort
size: 28235 bytes (33205 left)
wl0_txbf=1
wl0_txbf_en=1
wl1_txbf=1
wl1_txbf_en=1
wl_txbf=1
wl_txbf_en=1
alexdzn@RT-MIR3G:/tmp/home/root# cat /etc/Wireless/iNIC/iNIC_ap.dat | grep Bf
ITxBfEn=0
ETxBfIncapable=0
ETxBfEnCond=1
ETxBfeeEn=1
alexdzn@RT-MIR3G:/tmp/home/root# Connection closed by foreign host.
Now is good 270 /210 Mbit....Thank you 
Also I noticed WPS button mapping UI option in Andministration/System (may be hide it too)....

**Comment by lukasz1992** [comment]
Please enter

nvram set wl0_txbf=0
nvram set wl1_txbf=0
nvram set wl_txbf=0
nvram commit
reboot

**Comment by alexdzn2008** [comment]
Done. 190/190 Mbit Ipad, macbook pro 117/300 Mbit lan speed...

**Comment by lukasz1992** [comment]
Thanks for tests.

Depsite differences between releases https://github.com/lukasz1992/asuswrt-r3g/compare/3.0.0.4_382_51599..3.0.0.4_382_52072 are huge, the only two differences on WiFi drivers are:
- dab92d2d1b65e36a86a30444f98f888632a69978
- fix to allow Explicit Beamforming (it probably never worked on 51599) https://github.com/lukasz1992/asuswrt-r3g/commit/a4c1d067d94ec073f8c71dd2f326208616d3fa63#diff-1e43541d437603ebc8cfe45145bc5823 (lan.c)

To get the same behaviour as in 51559, you should disable both txbf options.
Then you should repeat the tests on 51559 to be sure that speeds differ.

**Comment by lukasz1992** [comment]
@alexdzn2008 Just to be sure, on disabled both txbf options post here the results of command
`cat /etc/Wireless/iNIC/iNIC_ap.dat | grep Bf`

**Comment by alexdzn2008** [comment]
alexdzn@RT-MIR3G:/tmp/home/root# cat /etc/Wireless/iNIC/iNIC_ap.dat | grep Bf
ITxBfEn=0
ETxBfEnCond=0
ETxBfIncapable=1
alexdzn@RT-MIR3G:/tmp/home/root# 
Speed test on macbook pro 90/190 Mbit (072 release)....

**Comment by lukasz1992** [comment]
No more ideas from my side. If it is possible, check again the 51599 release now (on the same settings)

**Comment by lukasz1992** [comment]
In my tests starting 2 years ago, I also do not get constant speeds for 5GHz WiFi (2.4GHz seems to be stable).

**Comment by lukasz1992** [comment]
I checked performance now, and it seems to be stable on Intel 7265 card.
As I do not have any other VHT device, and can not do anything more, I will close this ticket.

I decided to disable TxBf options by default, as drivers expose it after heavy patching; this feature is very experimental.

**Comment by alexdzn2008** [comment]
Latest release is fantastic, super fast...thank you ...only small note, wps is not working, so may be disable wps button mapping, to get 100% clean in use firmware for mi-r3g...)Rds, Alex

Отправлено с iPhone

**Comment by lukasz1992** [comment]
Hi, thanks for testing. TxBF is disabled by default now.

Actually it is a Asuswrt bug to display this setting, because all necessary build flags to enable WPS were turn off. I think this switch is not harmful.
