### ISSUE TITLE
Add ability to disable DNS rebinding protection

### ISSUE THREAD

**Issue by dartraiden** [lukasz1992/asuswrt-r3g#29]
There is a [VPN service](https://antizapret.prostovpn.org) whose DNS resolves addresses [blocked in Russia](https://en.wikipedia.org/wiki/Internet_censorship_in_Russia) as 10.x.x.x IPs.
Then the subnet is routed to this VPN, so that traffic only to these addresses goes through the VPN and other traffic bypasses VPN which reduces the load on VPN and allows it to remain free of charge.

It works perfectly on 3.0.0.4_382_51599, but do not work on 3.0.0.4_382_52072

Seems like dnmasq was updated and protection against  [DNS rebinding](https://en.wikipedia.org/wiki/DNS_rebinding) is enabled, so dnsmasqs filters out private IP addresses

**Comment by lukasz1992** [comment]
https://www.reddit.com/r/PleX/comments/bu40ar/dns_rebinding_issue_asus_router_maybe_i_should/

Looks like there is no way in OEM firmware to disable DNS rebinding.
You could anyway write a script to disable it manually and restart dnsmasq (place script in /jffs/.asusrouter).
