### ISSUE TITLE
Nand To SPI

### ISSUE THREAD

**Issue by vinhlilo90** [lukasz1992/asuswrt-r3g#30]
Hello thanks u for create this rom , can you create 1 rom for SPI chip please 
Thanks u very much

**Comment by lukasz1992** [comment]
Hi, what is flash mapping? After you provide me, I could write you a patch. Anyway this would not be supported, as I only have original R3G v1 router.

**Comment by vinhlilo90** [comment]
I have W25Q128FV , it have 16MB flash , and i using gen 3g v1 too , can you help me

**Comment by lukasz1992** [comment]
Chip is not a problem, it'd be supported. I need to know where and which partitions are stored (offsets and size).
Then we have to delete some things from image, to fit in 16MB flash.

**Comment by vinhlilo90** [comment]
I dont know , i will install breed and send you picture 😋😋

**Comment by lukasz1992** [comment]
Please send me a full flash dump of current firmware - we could guess map from it. Screenshoot from breed is not sufficient

**Comment by vinhlilo90** [comment]
Ok , send me a email i send to you , thanks u

**Comment by lukasz1992** [comment]
lukasz1992m@gmail.com

**Comment by vinhlilo90** [comment]
Here the link of Rom :https://drive.google.com/file/d/1-2Vn7X4mpM-mZgH5kkYSWBWvilrbW3Da/view?usp=drivesdk

**Comment by lukasz1992** [comment]
I need flash dump, not rom. I can do nothing with rom.

**Comment by vinhlilo90** [comment]
> I need flash dump, not rom. I can do nothing with rom.

So i need backup dump with CH341A ?

**Comment by vinhlilo90** [comment]
> I need flash dump, not rom. I can do nothing with rom.

https://drive.google.com/file/d/1-Bh1Dfo3m5CGrJsFZ8YihQfHyWq6FeP3/view?usp=drivesdk

**Comment by lukasz1992** [comment]
Please modify source code:

Replace in line 299:
BOOT_FLASH_TYPE=NAND MTK_NAND=y
with
BOOT_FLASH_TYPE=SPI

Remove in line 303:
NATNL_AICLOUD=y NATNL_AIHOME=y

Remove in line 304:
WEBDAV=y SMARTSYNCBASE=y TIMEMACHINE=y

And build image - it should work.

**Comment by vinhlilo90** [comment]
I dont know how to build :(

**Comment by lukasz1992** [comment]
Sorry, I do not have enough time for supporting other hardware

**Comment by vinhlilo90** [comment]
Thanks u for helping me

**Comment by adamnickster** [comment]
> Thanks u for helping me

Hi, I can build you image with parameters above if you want.

**Comment by vinhlilo90** [comment]
> > Thanks u for helping me
> 
> Hi, I can build you image with parameters above if you want.

Hope you can help me , thanks u very much
