### ISSUE TITLE
Can QoS work properly?

### ISSUE THREAD

**Issue by bailliesun** [lukasz1992/asuswrt-r3g#4]
Asus's QoS is very effective

**Comment by lukasz1992** [comment]
Should work, but it was not tested.
If it is not working, please disable HWNAT first.

**Comment by bailliesun** [comment]
Very good, It's working!
But 2.4G wifi is very slow.
Speedtest show me the speed is 4.07Mbps.

**Comment by lukasz1992** [comment]
I had much better speeds. Maybe there are interferences, other networks?
Could you put here `dmesg `output after the test?

**Comment by lukasz1992** [comment]
OK, thanks for testing.

**Comment by lukasz1992** [comment]
OK, thanks for testing.

If you use 20MHz channel and 1x1 radio, it is correct.

**Comment by qslfz** [comment]
The number of clients is 0。
