### ISSUE TITLE
IPv6 support broken?

### ISSUE THREAD

**Issue by tkso1997** [lukasz1992/asuswrt-r3g#5]
I love this firmware it works fantastic and wifi performance is great!
Unfortunately IPv6 is not working with mit ISP. I have a German cable connection with dual stack. Is there anything special I need to do to get an IPv6 on the wan interface? 
So far I tried 'native' and 'passthrough' but I don't get an IPv6.

Is there anything I could do to debug it?

Cheers!

**Comment by lukasz1992** [comment]
Hi, thanks for feedback!

There were some updates on network stack, and possibly a regression. My ISP does not support IPv6 and I have no way to test it.

1) Which release did you try?
Please check the second release and confirm if issue persists
2) Did you change anything on IPTV Settings? Could you provide me config on other router that should work?

**Comment by lukasz1992** [comment]
Please check the new version and open a new ticket if issue persists.
